db_user = "exampleuser"   #MySQL Database user
db_pass= "examplepass"   #MySQL Database user password
db_host= "examplehost"     #MySQL Database Host
db_name= "examplename"   #MySQL Database Name
repo_dir= "exampledir"     #Directory where the repositories are located
gh_user= "exampleuser"    #GitHub User
gh_token= "exampletoken"   #GitHub User Token
gh_pass= "examplepass"     #GitHub User Password
time_limit= "exampletime"  # period in minutes to check clone action 
smtp_host= "examplehost"  #smtp host server
smtp_port= "exampleport"  #port of smtp host server
smtp_user= "examplelogin" #smtp user server
smtp_pass= "examplepass" #smtp user password 
email_to= "examplemail"  #email account  
email_from= "examplemail" #email from
email_copy= "examplemail" #where to send copy email to
